### ISSUE TITLE
Add more types of mouse button events

### ISSUE THREAD

**Issue by mjcook000** [Brass-Monkery/Multitouch-Bugs#16]
If Multitouch could output other mouse button events besides left/ right/ middle (mouse button 1/ 2/ 3) then they could be captured by games, or utilities like Karabiner. (Karabiner lists a total of 32 mouse buttons)
slick program otherwise...

**Comment by rrhanson** [comment]
Thanks for the feedback! I'll plan to add this into the next release, which will probably go out shortly after Mojave gets released.

**Comment by rrhanson** [comment]
Mouse buttons 4-32 are now in [v1.7.0](https://multitouch.app/downloads/multitouch1.7.0.dmg).
