### ISSUE TITLE
When tap to click is enabled, executing a tap based gesture will select text

### ISSUE THREAD

**Issue by rxhanson** [Brass-Monkery/Multitouch-Bugs#2]
Multitouch v1.4.1

Configuration: 
Rest one finger and tap one to the left or right set to switch tabs in browser / tabbed application.
Tap to click is enabled in macOS.

In v1.4.0, the changing browser tabs would also pause video playing in a browser tab. In v1.4.1, video is no longer paused but text is selected on a browser page when the tabs are changed.

**Comment by rrhanson** [comment]
An update on this one:

I am not able to produce this issue on my 2016 MacBook Pro, but I am able to reproduce similar behavior on my 2010 MacBook Pro's built-in trackpad. I've witnessed some pretty odd behavior on it where blocking clicks after tap gestures have been performed will work most of the time, but sometimes multiple clicks seem to be registered for one tap when I am blocking them, and the subsequent clicks are not blockable. This seems to be buggy behavior with the older trackpad, but there should be a way to work around it. Still investigating.

**Comment by rrhanson** [comment]
Also note that if this behavior is noticed on a newer Mac, it could happen if the tap sensitivity is set low and the taps happen too quickly for the sensitivity setting. Try setting the tap sensitivity to high, and this should prevent taps from being ignored by Multitouch and falling through to execute a click when tap to click is enabled.
