### ISSUE TITLE
Multi monitor issues with clicks

### ISSUE THREAD

**Issue by royjs** [Brass-Monkery/Multitouch-Bugs#22]
I just started using Multitouch (trial for now) and I quickly stumbled upon an issue.
When using multiple monitors, the gestures that trigger a "click" action only work on the main monitor. 

I have a MacBook Pro with 2 external monitors. If I use a gesture for a middle-click (or any other click) on the laptop monitor, everything works fine but if I do the same on one of the other monitors the cursors "teleports" to the main monitor and the click is triggered there.

I'm using Mojave and I tested with the trackpad and a magic mouse.

**Comment by spacemunkay** [comment]
I was able to replicate this on Sierra with a single external monitor.  I had configured a right click and a linux middle click.  The weird thing is that the right click did not cause the issue initially.  I first noticed it using the Linux middle click.  After that, even after restarting the app, both the right click and Linux middle click continued to have the teleporting behavior.

**Comment by rrhanson** [comment]
Thanks for looking into it, @spacemunkay.

@royjs, thanks for reporting this! I'm pretty shocked that nobody has reported this before. I don't actually develop Mac stuff with an external monitor, so it's easy for me to see how this had slipped past my attention. My code for clicking literally used the "main" monitor's coordinates when calculating where to execute a click (sorry!). I'll be posting a release soon with a fix.

**Comment by royjs** [comment]
@rxhanson I just tried it and it works great now. Thank you for the quick fix.
