### ISSUE TITLE
Add "scroll to top" and "scroll to bottom" actions

### ISSUE THREAD

**Issue by ab1470** [Brass-Monkery/Multitouch-Bugs#23]
Ideally this could be used in conjunction with multi-finger swipes. For example, swiping up with three fingers will jump to the top of the page, and swiping down with three fingers jumps to the bottom.

**Comment by rxhanson** [comment]
@ab1470 
This can be done with keyboard shortcuts (cmd+up arrow, cmd+down arrow). Would that be sufficient to your expectation?

**Comment by ab1470** [comment]
Yes, that would be fine. I should have thought of that!

**Comment by rxhanson** [comment]
Awesome. At the very least, I'll take this request as a "+1" for adding the three/four finger swipe gestures.
