### ISSUE TITLE
switch app left not working, it still switch apps right

### ISSUE THREAD

**Issue by quanru** [Brass-Monkery/Multitouch-Bugs#32]
![image](https://user-images.githubusercontent.com/11739753/49094739-e3c82000-f2a1-11e8-91a3-b75836aed007.png)

osx:
![image](https://user-images.githubusercontent.com/11739753/49094797-0fe3a100-f2a2-11e8-9b73-c5db50c6363e.png)

multitouch:
![image](https://user-images.githubusercontent.com/11739753/49094827-1f62ea00-f2a2-11e8-9f41-aa7b384d73ce.png)

**Comment by rxhanson** [comment]
I think the issue might be that you have mistakenly assigned actions to the opposite gesture that you intended. 

In your screenshot, you have "rest two and tap one to the right" switching applications to the left, and you have "rest two and tap one to the left" switching applications to the right. I would have expected the opposite.

Let me know if that's not the issue.

**Comment by quanru** [comment]
@rxhanson i want to navigate the applications by these 2 actions

**Comment by rxhanson** [comment]
@quanru, I think your left and right should be switched.

![switchgestures](https://user-images.githubusercontent.com/13651296/49176162-8045fd00-f34a-11e8-812e-109a88e4e3d4.png)

This is how mine is configured:

<img width="186" alt="screen shot 2018-11-28 at 8 14 21 pm" src="https://user-images.githubusercontent.com/13651296/49176175-850ab100-f34a-11e8-87a2-4cdf83d5ff4c.png">

Does that fix your issue?

**Comment by quanru** [comment]
sorry, i found out that it was the [cmdtab](http://www.yingdev.com/projects/cmdtap)'s problem
