### ISSUE TITLE
Won't trigger with InDesign CC 2019 on mac

### ISSUE THREAD

**Issue by graphikjam** [Brass-Monkery/Multitouch-Bugs#36]
Gestures work everywhere else, but when I'm in InDesign CC 2019, nothing happens. I'm on High Sierra Mac. 

If I remember correctly, CC 2018 worked fine, so maybe something changed in CC 2019? Illustrator, Photoshop, all fine...just InDesign

Any ideas what's going on?

**Comment by rxhanson** [comment]
Weird. I'll download the free trial of InDesign and see if I can figure out why/how that would happen.

**Comment by graphikjam** [comment]
If there’s anything can do to help, let me know. 


John Vandenberg

Graphik Jam Inc
Industrial Strength Design on Paper and Online
Aurora, Illinois

Office: 630-851-2120

**Comment by graphikjam** [comment]
not disabled, double checked. Must be something else. I’m going update to Mojave soon enough, I’ll see what happens then.

Thanks for the quick reply.



John R. Vandenberg, President

Graphik Jam Inc.
Graphic Design | Web Design

Aurora, Illinois
Office: 630-851-2120

johnv@graphikjam.com

**Comment by rxhanson** [comment]
Closing this out since it's been a while. If you have any updates here, feel free to reopen the issue. Thanks!
