### ISSUE TITLE
Swiping between spaces triggers paste in Terminal

### ISSUE THREAD

**Issue by lorenzofanchi** [Brass-Monkery/Multitouch-Bugs#38]
Hi, when I swipe between spaces and a Terminal window is active in the destination space, a paste action (or maybe Cmd + Arrow Up?) action is triggered. Doesn't happen when Multitouch is de-activated.

Cheers

**Comment by rxhanson** [comment]
The swipe between spaces - is that a 3 finger trackpad swipe, 4 finger trackpad swipe, or 2 finger magic mouse swipe? 

My initial thought is that Multitouch may be interpreting your swipe as a different gesture execution - for example, maybe a rest 3 tap 1 is being executed when swiping with four fingers? 

Do you have a configuration that would be executing a paste (or cmd+arrow up) for another gesture that may be inadvertently executed? If we can narrow it down, then I can determine which gestures would need to be improved to be less likely to be accidentally executed - provided that's the issue.

**Comment by lorenzofanchi** [comment]
The swipe that triggers it is a four-finger trackpad swipe. Strangely, it's not consistent, as in, it doesn't trigger each time. However, when it happens, quitting multitouch fixes it and restarting multitouch brings it back.

My config:
<img width="402" alt="Screenshot 2019-04-08 at 15 45 29" src="https://user-images.githubusercontent.com/770285/55729026-a0cb4580-5a15-11e9-9613-5e0963fd7fc3.png">

**Comment by lorenzofanchi** [comment]
Okay, I just managed to trigger it consistently for a while with a four-finger down swipe, before it magically stopped triggering it.

**Comment by lorenzofanchi** [comment]
alright, back with a video. managed to consistently trigger the issue now:

https://streamable.com/lckpf

As you can see, as I'm swiping between spaces, `ls` is repeatedly pasted in iTerm. Once I quit Multitouch, the issue is gone. I don't have this in the video, but after restarting Multitouch, the issue comes back immediately...

**Comment by lorenzofanchi** [comment]
Another note, for now, I only seem to be able to trigger this in Terminal and iTerm. Other fullscreen apps with input boxes don't seem to be affected

**Comment by rxhanson** [comment]
Ah, ok. Really sorry I didn't dig into this after your comment from 25 days ago. What you're seeing is the three finger tap executing when it shouldn't. I'll make some adjustments to it in the next release I push out. Middle clicks in terminal (and iTerm) will execute a paste from the highlight clipboard - the last selected text will be saved there. This mimics the os-wide middle click behavior in linux (a feature that I've always missed in OSX/macOS). You wouldn't notice other apps doing anything with an accidental middle click execution most likely.

Thanks for taking the time to make a video. I'll post back here when I drop another release.

**Comment by lorenzofanchi** [comment]
Cool, never knew that! Would be great to have this fixed as it's become a daily nuisance for me. This is actually my biggest gripe with Multitouch, so I hope it's an easy fix :)

**Comment by rxhanson** [comment]
I was hoping this would be a straightforward fix, but it's slightly more complicated so I decided to put this in a beta release first, v1.10.4 on [https://multitouch.app/versions](https://multitouch.app/versions). Let me know if that fixes it for you or not.

**Comment by lorenzofanchi** [comment]
@rxhanson In my testing so far, this issue seems to be fixed!

**Comment by lorenzofanchi** [comment]
Okay, I take that back, I did manage to trigger it once. Harder though, apparently

**Comment by rxhanson** [comment]
Alright, v1.10.5 on the [versions page](https://multitouch.app/versions) has an updated fix that should do it. At this point, if you still have accidental triggers then I can tweak the internal setting for how much movement determines that a tap should not be executed. I think it should be good as it is now though.

**Comment by rxhanson** [comment]
I released v1.11, which includes these changes, and I pulled down v1.10.5. Let me know if you see any issues there.

**Comment by rxhanson** [comment]
Closing this one out, but just open it back up if you experience any more accidental triggers.
