### ISSUE TITLE
Add to homebrew-cask

### ISSUE THREAD

**Issue by lorenzofanchi** [Brass-Monkery/Multitouch-Bugs#41]
Hi Ryan, it would be great if multitouch could be added to homebrew-cask for easy installation and updating. Currently, the download URL seems to be generated on the fly with a token, seemingly preventing automated brew installation. Any comment? Thanks!

**Comment by lorenzofanchi** [comment]
I made a start with a brew cask formula below. The sections with $$$ are missing.

```
cask 'shuttle' do
  version '1.11'
  sha256 '$$$'

  url "https://$$$/releases/download/multitouch#{version}.dmg"
  appcast "https://$$$/appcast#{version}.xml"
  name 'Multitouch'
  homepage 'https://multitouch.app/'

  app 'Multitouch.app'

  zap trash: '~/Library/Preferences/com.brassmonkery.Multitouch'
end
```

**Comment by rxhanson** [comment]
Hey, thanks for posting your start on this. It's one of those things that forever gets pushed back on my todo for Multitouch, so now is as good a time as any to finally get this done. 

As you might suspect, the token is there for validation that the download is actually coming from a visitor to https://multitouch.app. I've had people attack the site's downloads, so I put a number of barriers in place to prevent attacks. As such, I'll need to add some special things in place server side to handle brew cask. 

I'll take your start on the brew cask formula and post back here when things are ready.

**Comment by rxhanson** [comment]
Ok, the homebrew cask is just awaiting merge by the homebrew team:
https://github.com/Homebrew/homebrew-cask/pull/63498

**Comment by rxhanson** [comment]
Alright, Multitouch is now available on brew cask.
`brew cask install multitouch`
This of course bumps up priority on another one of my todos that keeps getting pushed back: iCloud syncing Multitouch settings. Thanks again for jumpstarting me on this task.

**Comment by cotfas** [comment]
"iCloud syncing Multitouch settings" Will be nice to have. :)

**Comment by rxhanson** [comment]
@cotfas iCloud syncing is in Multitouch. It's on my TODO to add a preference to the UI that shows it, as a lot of users are unaware that it exists. If you experience issues with it, feel free to file a separate issue.

**Comment by cotfas** [comment]
Otherwise where is the location of the settings file on disk?

**Comment by rxhanson** [comment]
~/Library/Preferences/com.brassmonkery.Multitouch.plist

If you make changes to the plist for items that are synced via iCloud, they will be overwritten by the iCloud sync.

Therefore, if you want to change the plist directly for these items, you'll need to disable iCloud sync:

`defaults write com.brassmonkery.Multitouch iCloudOverride -bool true`
