### ISSUE TITLE
Rest one tap one requires 2 to 3 taps to work

### ISSUE THREAD

**Issue by rxhanson** [Brass-Monkery/Multitouch-Bugs#42]
rest one finger and tap to left or right seems to work just perfect with jiTouch but with Multitouch I am having few problems like 
1. many times it will require 2 to 3 taps just to get to another tab which is very annoying but when gestures work it is smooth
2. sometimes instead of switching tabs it will play the background video 

I tried to play with settings but it made it worse and I feel like I have to tap pretty firmly to make the gestures work.
Also I would say that most people use 2 fingers on their trackpad and this feature is a must for me atleast. 
Which gesture you use to switch your tabs if not this one?

_Originally posted by @yooyoyo in https://github.com/Brass-Monkery/Multitouch-Bugs/issues/30#issuecomment-494461531_

**Comment by rxhanson** [comment]
For 1, make sure that you have Tap Sensitivity set to **High**. That really should make it pretty easy to execute this gesture. Is this something intermittent, or is it every time you try to execute a rest one tap one?
Do you have any other apps running that might be listening to macOS gestures?

For 2, can you let me know which browser, and give me an example site that you experience this on? Multitouch is basically just executing keystrokes to switch tabs, so if a video player somehow responds to the same keystrokes as a tab switch keyboard shortcut then this would happen. That's pretty unlikely, so maybe I can reproduce it and figure out what's going on.

**Comment by yooyoyo** [comment]
1. I tried high sensitivity but that did not help, it actually made it worse and it does seem to occur specifically when I try to execute rest one tap gesture. When it works it works fine but when it does not it will require 2-3 taps. I am facing problem with this specific gesture. Jitouch works just perfectly without any misfires. I restarted the app and to some extent it made it better but after minutes of usage there were misfires. It responds and then it does not respond. Rest one and tap requires refining. I cannot get the hang of this, I just keep on going back to JiTouch. Please make this your priority gesture to fix as Jitouch is pretty limited in what it can do and this app is awesome except this gesture.
2. I had jiTouch running but when testing Multitouch I had switched it off 
3. I am using safari and this happens on every other website.

**Comment by rxhanson** [comment]
Hopefully I can narrow this down a little more and figure out what's going on. Can you post your config? You can copy it to your clipboard from Help -> About Multitouch -> Copy Debug Info to Clipboard. 

Just for the sake of testing: if you set another gesture to switch tabs, like three finger click, do you still experience the same issue?

Do background videos play when using another browser other than Safari?

Try checking the box for "Avoid private framework" in the Multitouch preferences. You'll be prompted to let the app restart. Let me know if you notice any difference in behavior.

**Comment by yooyoyo** [comment]
"Avoid private framework" - it breaks the entire gesture
setting 3 finger click works as expected though I did not test that rigorously as I am not habitual to that  gesture for tab switching - I use it to close my open tabs and it works great
I am using default configuration as any change to settings actually makes it worse.

I don't know why it misfires... I am trying to figure that out. All I can say is when it works it works great but when it misfires, it will misfire at-least twice. Initially I thought when my trackpad was idle and I try to use it for the first time it will misfire but I have had misfires when in continuous use too.
It requires me to tap at-least twice and I can also say that I have had more TAP LEFT misfires than the right

**Comment by rxhanson** [comment]
I think I'm going to have to set up a debug build and send it your way to get some logs on what's going on. If you're up for running it, I'll let you know when it's ready and I will provide instructions on how to obtain logs to send back.

**Comment by rxhanson** [comment]
Alright, sorry for the delayed follow-up on this. I think I was able to reproduce this, although extremely infrequently. I made some changes that _should_ fix what you were experiencing. The changes are in a beta (v1.11.3) that can be download at[https://multitouch.app/versions](https://multitouch.app/versions). Please give it a try and let me know if it fixes your issue or not.

**Comment by rxhanson** [comment]
As far as I can tell, this is fixed. If it's not, feel free to reopen it. Thanks.
