### ISSUE TITLE
Firefox tab switching

### ISSUE THREAD

**Issue by lorenzofanchi** [Brass-Monkery/Multitouch-Bugs#43]
Hi @rxhanson, in the latest (v67) version of Firefox the "Switch tabs left/right" actions don't work as expected. "Switch tabs left" does nothing, while "Switch tabs right" seems to open a tab preview overlay.

Running v1.11.4 of Multitouch

**Comment by rxhanson** [comment]
Thanks for the heads up. I put a fix in v1.11.5 (beta) for this. Hopefully looking to do an official release soon.

**Comment by lorenzofanchi** [comment]
new release fixed it, thanks!
